blank_issues_enabled: false
contact_links:
  - name: VirtualDesktop-OpenXR Homepage
    url: https://github.com/mbucchia/VirtualDesktop-OpenXR/wiki
    about: The homepage has a lot of useful information, including Compatibility list.
  - name: OpenXR Toolkit Homepage
    url: https://mbucchia.github.io/OpenXR-Toolkit/
    about: The homepage has A LOT OF INFORMATION if you are using OpenXR Toolkit. Check there first for the answer to your questions/issues. There is a Search bar at the top.
